name: Build FVClient APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Telegram FOSS Safely
      uses: actions/checkout@v4
      with:
        repository: 'Telegram-FOSS-Team/Telegram-FOSS'
        fetch-depth: 1
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Inject FVClient Settings and Proxy
      run: |
        sed -i 's|public static int APP_ID = .*|public static int APP_ID = 30355297;|g' TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java
        sed -i 's|public static String APP_HASH = .*|public static String APP_HASH = "185d33731f4ac88b116e5b6c8f61b22c";|g' TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java
        
        find TMessagesProj/src/main/res/ -name "strings.xml" -exec sed -i 's|AppName">.*<|AppName">FVClient<|g' {} +
        find TMessagesProj/src/main/res/ -name "strings.xml" -exec sed -i 's|Telegram|FVClient|g' {} +

        sed -i 's|currentProxyAddress = .*|currentProxyAddress = "109.236.83.136";|g' TMessagesProj/src/main/java/org/telegram/tgnet/ConnectionsManager.java
        sed -i 's|currentProxyPort = .*|currentProxyPort = 1080;|g' TMessagesProj/src/main/java/org/telegram/tgnet/ConnectionsManager.java
        sed -i 's|currentProxyType = .*|currentProxyType = 1;|g' TMessagesProj/src/main/java/org/telegram/tgnet/ConnectionsManager.java

    - name: Grant Execute Permission
      run: chmod +x gradlew

    - name: Build Android APK
      run: |
        ./gradlew assembleAfossDebug \
          -PapplicationId=://fvclient.com \
          --no-daemon \
          --stacktrace

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: FVClient-RuStore-Release
        path: TMessagesProj/build/outputs/apk/afoss/debug/*.apk
